# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
 - uat
 - feature/*

pool:
  vmImage: 'macos-latest'

jobs:
  - job: build_job
    steps:
      - task: DownloadSecureFile@1
        name: releaseKeystore
        displayName: 'Download release keystore'
        inputs:
          secureFile: 'release.keystore'

      - task: DownloadSecureFile@1
        name: debugKeystore
        displayName: 'Download debug keystore'
        inputs:
          secureFile: 'debug.keystore'

      - task: DownloadSecureFile@1
        name: baseProperties
        displayName: 'Download Properties'
        inputs:
          secureFile: 'base.properties'

      - task: DownloadSecureFile@1
        name: firebaseCredential
        displayName: 'Download firebase credentials'
        inputs:
          secureFile: 'firebase_credentials.json'

      - script: |
          sudo chown root:root $(baseProperties.secureFilePath)
          sudo chmod a+r $(baseProperties.secureFilePath)
          sudo mv $(baseProperties.secureFilePath) $(Build.SourcesDirectory)
          sudo mv $(firebaseCredential.secureFilePath) $(Build.SourcesDirectory)
          displayName: 'Move files to root project'

          - script: |
          cd $(Build.SourcesDirectory)
          echo -e "\nKEYSTORE_FILE = $(releaseKeystore.secureFilePath)\nDEBUG_KEYSTORE_FILE = $(debugKeystore.secureFilePath)" >> base.properties
        displayName: 'Set up jks file path in properties.'

      - bash: echo "FIREBASE_ANDROID_ID = $FIREBASE_APP_ID"
        env:
          FIREBASE_APP_ID: $(FIREBASE_ANDROID_ID)
        displayName: 'Set up firebase id in Environment.'

      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'

      - script: |
          java -version
        env:
          JAVA_HOME: $(JAVA_HOME_11_X64)
          PATH: $(JAVA_HOME_11_X64)/bin:$(PATH)
        displayName: 'Set Java Environment Variables'

      - script: chmod +x ./gradlew
        displayName: 'Installed Gradlew'

  - job: sit_job
    dependsOn: build_job
    condition: and(succeeded('build_job'), eq(variables['Build.SourceBranch'], 'refs/heads/feature/*'))
    steps:
     - script: |
         fastlane clean
         fastlane distribute firebase_id:$(FIREBASE_ANDROID_ID) build_type: "sit"
       displayName: 'Build apk and push Firebase App Distributions'

  - job: uat_job
    dependsOn: build_job
    condition: and(succeeded('build_job'), eq(variables['Build.SourceBranch'], 'refs/heads/uat'))
    steps:
      - script: |
          fastlane clean
          fastlane distribute firebase_id:$(FIREBASE_ANDROID_ID) build_type: "uat"
        displayName: 'Build apk and push Firebase App Distributions'

#  - job: master_job
#    dependsOn: build_job
#    condition: and(succeeded('build_job'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
#    steps:
#        - script: |
#            fastlane clean
#            fastlane distribute firebase_id:$(FIREBASE_ANDROID_ID)
#          displayName: 'Build apk and push Firebase App Distributions'