# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

#trigger:
#  - develop

pool:
  vmImage: 'macos-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: |
      java -version
    env:
      JAVA_HOME: $(JAVA_HOME_11_X64)
      PATH: $(JAVA_HOME_11_X64)/bin:$(PATH)
    displayName: 'Set Java Environment Variables'

  - task: DownloadSecureFile@1
    name: keystore
    displayName: 'Download keystore'
    inputs:
      secureFile: 'release.keystore'

  - task: DownloadSecureFile@1
    name: baseProperties
    displayName: 'Download Properties'
    inputs:
      secureFile: 'base.properties'

  - script: |
      sudo chown root:root $(baseProperties.secureFilePath)
      sudo chmod a+r $(baseProperties.secureFilePath)
      sudo mv $(baseProperties.secureFilePath) $(Build.SourcesDirectory)
    displayName: 'Move file to root project'

  - script: |
      cd $(Build.SourcesDirectory)
      filePath = keystore.secureFilePath
      echo "\nKEYSTORE_FILE = $filePath" >> base.properties
      cat base.properties
    displayName: 'Set up jks file path in properties.'

  - script: chmod +x ./gradlew
    displayName: 'Installed Gradlew'

  - script: fastlane run_build
    displayName: 'Gradlew Building'
