# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Check version update."
  before_all do
    update_fastlane
  end

  desc "Runs all the tests"
  lane :tests do
    gradle(task: "test")
  end

  desc "Clear project build folder."
  lane :clean do
    gradle(tasks: ["clean"])
  end

  desc "Lane for distributing app using Firebase App Distributions"
  lane :distribute do |options|
    build_android_app(
      task: "assemble",
      build_type: options[:build_type]
    )
    commit = last_git_commit
    firebase_app_distribution(
        service_credentials_file: "firebase_credentials.json",
        app: ENV["FIREBASE_ANDROID_ID"],
        release_notes: commit[:message],
        groups: "ctbc_testers"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy_google_play do
    build_android_app(
      task: "assemble",
      build_type: "release"
    )
    upload_to_play_store(
        track: 'internal',
        mapping: "app/build/outputs/mapping/release/mapping.txt",
        skip_upload_apk: true,
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        validate_only: true
    )
  end
end
